//--------------------------------------------------------------------------
// (C) Copyright 2000 Microsoft Corporation.  All Rights Reserved.
//
// THIS CODE AND INFORMATION IS PROVIDED "AS-IS" WITHOUT WARRANTY OF
// ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO
// THE IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A
// PARTICULAR PURPOSE.
//
// --- THIS CODE IS NOT SUPPORTED BY MICROSOFT ---
#define DISPID_GETHWND   500 
#define DISPID_SAYHELLO  501
#define DISPID_SETPARENT 502
#define DISPID_NAVIGATE  503
#define DISPID_SCRAP	 504
#define DISPID_SUBSCRIBE 505
#define DISPID_READON	 506
#define DISPID_READPOST	 507
#define DISPID_GETWB	 508

