//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by FISH.rc
//
#define ID_BUTTON_CHECK                 3
#define IDD_ABOUTBOX                    100
#define IDD_VIEW_SUBSCRIBE              101
#define IDR_FISH                        102
#define IDP_SOCKETS_INIT_FAILED         104
#define IDR_FISHIECONTROL               107
#define IDC_INFORMATION_TAB_CTRL        107
#define IDB_LISTCTRL_COLUMNHEADER_SPAN  108
#define IDB_LISTCTRL_COLUMNHEADER_SPAN_N 108
#define IDB_LISTCTRL_COLUMNHEADER_START 109
#define IDB_LISTCTRL_COLUMNHEADER_START_N 109
#define IDB_LISTCTRL_COLUMNHEADER_END   110
#define IDB_LISTCTRL_COLUMNHEADER_END_N 110
#define IDB_LISTCTRL_HORIZONTAL_SCROLLBAR_THUMB 111
#define IDB_LISTCTRL_HORIZONTAL_SCROLLBAR_RIGHTARROW 112
#define IDB_LISTCTRL_HORIZONTAL_SCROLLBAR_SPAN 113
#define IDB_LISTCTRL_HORIZONTAL_SCROLLBAR_LEFTARROW 114
#define IDB_LISTCTRL_VERTICLE_SCROLLBAR_UPARROW 115
#define IDB_LISTCTRL_VERTICLE_SCROLLBAR_SPAN 116
#define IDB_LISTCTRL_VERTICLE_SCROLLBAR_THUMB 117
#define IDB_LISTCTRL_VERTICLE_SCROLLBAR_DOWNARROW 118
#define IDB_LISTCTRL_VERTICLE_SCROLLBAR_TOP 119
#define IDB_LISTCTRL_VERTICLE_SCROLLBAR_BOTTOM 120
#define ID_LIST_HD_GOTO_PREV            121
#define ID_LIST_HD_GOTO_NEXT            123
#define IDR_MAINFRAME                   128
#define IDR_FISHTYPE                    129
#define IDD_VIEW_INFORMATION            130
#define IDD_DLG_SUBSCRIBE               131
#define IDD_DLG_INFORMATION             132
#define IDD_DLG_BROWSER                 133
#define IDD_DLG_RSSLIST                 134
#define IDD_DLG_RSSBROWSER              135
#define IDD_DLG_RSSMAIN                 136
#define IDD_DLG_SEARCH                  137
#define IDD_DLG_EXPLORERBAR             138
#define IDB_REPOSITORY_ANIMATE_ICONS    140
#define IDB_REPOSITORY_ANIMATE_SANDTIMER 140
#define IDB_REPOSITORY_CHANNEL_ICONS    141
#define IDB_REPOSITORY_GROUP_BG         142
#define IDB_REPOSITORY_GROUP_BG_N       142
#define IDB_REPOSITORY_GROUP_ICONS      143
#define IDD_REPOSITORY_ITEM_PROPERTY    144
#define IDR_ATLBR_MENU                  145
#define IDB_SPLT_V                      146
#define IDB_SPLT_H                      147
#define IDB_SPLT_TRANS                  148
#define IDB_COMBO_N                     149
#define IDB_COMBO_O                     150
#define IDB_COMBO_P                     151
#define IDB_INFORMATION_TAB_ICONS       152
#define IDB_TABCTRL_ICONS               152
#define IDC_INFORMATION_TAB_COPY        153
#define IDC_INFORMATION_TAB_MOVE        154
#define IDR_MENU_FOR_EVENT_HANDLING     158
#define IDB_SPLITTER_HORIZONTAL_BMP     160
#define IDB_SPLITTER_VERTICAL_BMP       161
#define IDR_MENU_SUBSCRIBE              162
#define IDB_REPOSITORY_ADDCHANNEL_P     164
#define IDB_REPOSITORY_ADDCHANNEL_N     165
#define IDB_REPOSITORY_ADDCHANNEL_O     166
#define IDB_REPOSITORY_ADDGROUP_P       167
#define IDB_REPOSITORY_ADDGROUP_N       168
#define IDB_REPOSITORY_ADDGROUP_O       169
#define IDB_REPOSITORY_ADDKEYWORD_P     170
#define IDB_REPOSITORY_ADDKEYWORD_N     171
#define IDB_REPOSITORY_ADDKEYWORD_O     172
#define IDB_REPOSITORY_ADDSCRAP_P       173
#define IDB_REPOSITORY_ADDSCRAP_N       174
#define IDB_REPOSITORY_ADDSCRAP_O       175
#define IDB_REPOSITORY_REFRESH_P        176
#define IDB_REPOSITORY_REFRESH_N        177
#define IDB_REPOSITORY_REFRESH_O        178
#define IDB_TRAY_CONNECTING             180
#define IDB_TRAY_DOWNLOADING            181
#define IDB_TRAY_NORMAL                 182
#define IDB_TRAY_OFF                    183
#define IDB_TRAY_UNREAD                 184
#define IDB_MAINFRAME_ALLSYSMENU_ICONS  185
#define IDB_MAINFRAME_MINIMIZE_N        186
#define IDB_MAINFRAME_MINIMIZE_O        187
#define IDB_MAINFRAME_MINIMIZE_P        188
#define IDB_MAINFRAME_CLOSE_O           189
#define IDB_MAINFRAME_PRESIZE_O         190
#define IDB_MAINFRAME_MAXIMIZE_N        191
#define IDB_MAINFRAME_PRESIZE_N         192
#define IDB_MAINFRAME_CLOSE_N           193
#define IDB_MAINFRAME_MAXIMIZE_O        194
#define IDB_MAINFRAME_MAXIMIZE_P        195
#define IDB_MAINFRAME_PRESIZE_P         196
#define IDB_MAINFRAME_CLOSE_P           197
#define IDR_MENU_TRAY                   198
#define IDD_CHG_PORT_DLG                199
#define IDB_NOTIFIER_ICON               200
#define IDB_NOTIFIER_BG                 202
#define IDR_DEFAULT_XSLT                203
#define IDR_MENU_VIEWINFO               204
#define IDB_LISTCTRL_ATTENTION_PROGRESSBAR 205
#define IDB_MAINFRAME_TOPRIGHT          207
#define IDB_MAINFRAME_TOPLEFT           208
#define IDB_MAINFRAME_BOTTOMLEFT        209
#define IDB_MAINFRAME_BOTTOMRIGHT       210
#define IDB_MAINFRAME_RIGHT             212
#define IDB_MAINFRAME_BOTTOMCENTER      213
#define IDB_MAINFRAME_LEFT              214
#define IDB_REPOSITORY_DLG_BKGND        215
#define IDB_SRCHL_BTN_P                 252
#define IDB_SRCHL_BTN_N                 254
#define IDB_SRCHL_BTN_O                 255
#define IDB_SRCHN_BTN_P                 256
#define IDB_SRCHN_BTN_N                 258
#define IDB_SRCHN_BTN_O                 259
#define IDB_SRCHR_BTN_P                 260
#define IDB_SRCHR_BTN_N                 262
#define IDB_SRCHR_BTN_O                 263
#define IDB_BG_DLG_SRCH                 264
#define IDB_SRCH_DLG_BG                 264
#define IDB_SRCH_NETWORK_LOADNUM_0_P    265
#define IDB_SRCH_NETWORK_0_N            266
#define IDB_SRCH_NETWORK_0_O            267
#define IDB_SRCH_NETWORK_0_P            268
#define IDB_SRCH_NETWORK_LOADNUM_0_N    269
#define IDB_SRCH_NETWORK_LOADNUM_0_O    270
#define IDB_SRCH_NETWORK_LOADNUM_1_P    271
#define IDB_SRCH_NETWORK_1_N            272
#define IDB_SRCH_NETWORK_1_O            273
#define IDB_SRCH_NETWORK_1_P            274
#define IDB_SRCH_NETWORK_LOADNUM_1_N    275
#define IDB_SRCH_NETWORK_LOADNUM_1_O    276
#define IDB_SRCH_NETWORK_LOADNUM_2_N    277
#define IDB_SRCH_NETWORK_LOADNUM_2_O    278
#define IDB_SRCH_NETWORK_LOADNUM_2_P    279
#define IDB_SRCH_NETWORK_2_N            280
#define IDB_SRCH_NETWORK_2_O            281
#define IDB_SRCH_NETWORK_2_P            282
#define IDB_SRCH_NETWORK_LOADNUM_3_N    283
#define IDB_SRCH_NETWORK_LOADNUM_3_O    284
#define IDB_SRCH_NETWORK_LOADNUM_3_P    285
#define IDB_SRCH_NETWORK_3_N            286
#define IDB_SRCH_NETWORK_3_O            287
#define IDB_SRCH_NETWORK_3_P            288
#define IDB_SRCH_TAG                    289
#define IDB_SRCH_GO                     290
#define IDB_MAINLIST_SUBSCRIBE_O        291
#define IDB_VIEWINFO_BTN_SUBSCRIBE_O    291
#define IDB_MAINLIST_NEWTAB_P           292
#define IDB_VIEWINFO_BTN_NEWTAB_P       292
#define IDB_MAINLIST_NEWTAB_N           293
#define IDB_VIEWINFO_BTN_NEWTAB_N       293
#define IDB_MAINLIST_NEWTAB_O           294
#define IDB_VIEWINFO_BTN_NEWTAB_O       294
#define IDB_MAINLIST_SAVE_P             295
#define IDB_VIEWINFO_BTN_SAVE_P         295
#define IDB_MAINLIST_SAVE_N             296
#define IDB_VIEWINFO_BTN_SAVE_N         296
#define IDB_MAINLIST_SAVE_O             297
#define IDB_VIEWINFO_BTN_SAVE_O         297
#define IDB_MAINLIST_STYLE_P            298
#define IDB_VIEWINFO_BTN_STYLE_P        298
#define IDB_MAINLIST_STYLE_N            299
#define IDB_VIEWINFO_BTN_STYLE_N        299
#define IDB_MAINLIST_STYLE_O            300
#define IDB_VIEWINFO_BTN_STYLE_O        300
#define IDB_MAINLIST_SUBSCRIBE_P        301
#define IDB_VIEWINFO_BTN_SUBSCRIBE_P    301
#define IDB_MAINLIST_SUBSCRIBE_N        302
#define IDB_VIEWINFO_BTN_SUBSCRIBE_N    302
#define IDD_VIEW_NAVIGATIONPANE         303
#define IDB_TABCTRL_GOTO_MAINLIST_BTN_P 304
#define IDB_TABCTRL_GOTO_MAINLIST_BTN_N 305
#define IDB_SRCHR_ALL_BTN_P             306
#define IDB_SRCHR_ALL_BTN_D             307
#define IDB_SRCHR_ALL_BTN_N             308
#define IDB_SRCHR_ALL_BTN_O             309
#define IDB_SRCHR_LOCAL_BTN_D           310
#define IDB_SRCHR_LOCAL_BTN_N           311
#define IDB_SRCHR_LOCAL_BTN_O           312
#define IDB_SRCHR_LOCAL_BTN_P           313
#define IDB_EXPLORERBAR_STOP_P          315
#define IDB_EXPLORERBAR_BACK_N          316
#define IDB_EXPLORERBAR_BACK_O          317
#define IDB_EXPLORERBAR_BACK_P          318
#define IDB_EXPLORERBAR_BKGND           319
#define IDB_EXPLORERBAR_FORWARD_N       320
#define IDB_EXPLORERBAR_FORWARD_O       321
#define IDB_EXPLORERBAR_FORWARD_P       322
#define IDB_EXPLORERBAR_BKGND_MIDDLE    323
#define IDB_EXPLORERBAR_REFRESH_N       324
#define IDB_EXPLORERBAR_REFRESH_O       325
#define IDB_EXPLORERBAR_REFRESH_P       326
#define IDB_EXPLORERBAR_STOP_N          327
#define IDB_EXPLORERBAR_STOP_O          328
#define IDB_EXPLORERBAR_STOP_D          329
#define IDB_EXPLORERBAR_BACK_D          330
#define IDB_EXPLORERBAR_FORWARD_D       331
#define IDB_EXPLORERBAR_REFRESH_D       332
#define IDB_EXPLORERBAR_COMBO_BTN       333
#define IDB_VIEWINFO_NAV_BTN_NEXT3_O    334
#define IDB_VIEWINFO_NAV_BTN_BACK1_P    335
#define IDB_VIEWINFO_NAV_BTN_BACK1_N    336
#define IDB_VIEWINFO_NAV_BTN_BACK1_O    337
#define IDB_VIEWINFO_NAV_BTN_BACK2_P    338
#define IDB_VIEWINFO_NAV_BTN_BACK2_N    339
#define IDB_VIEWINFO_NAV_BTN_BACK2_O    340
#define IDB_VIEWINFO_NAV_BTN_BACK3_P    341
#define IDB_VIEWINFO_NAV_BTN_BACK3_N    342
#define IDB_VIEWINFO_NAV_BTN_BACK3_O    343
#define IDB_VIEWINFO_NAV_CENTER_P       344
#define IDB_VIEWINFO_NAV_CENTER_N       345
#define IDB_VIEWINFO_NAV_BTN_NEXT1_P    346
#define IDB_VIEWINFO_NAV_BTN_NEXT1_N    347
#define IDB_VIEWINFO_NAV_BTN_NEXT3_P    348
#define IDB_VIEWINFO_NAV_BTN_NEXT3_N    349
#define IDB_VIEWINFO_NAV_BTN_NEXT1_O    350
#define IDB_VIEWINFO_NAV_BTN_NEXT2_P    351
#define IDB_VIEWINFO_NAV_BTN_NEXT2_N    352
#define IDB_VIEWINFO_NAV_BTN_NEXT2_O    353
#define IDB_SUBDLG_LEFT                 354
#define IDB_SUBDLG_RIGHT                355
#define IDB_SUBDLG_TITLE                356
#define IDB_SUBDLG_LOGO                 357
#define IDB_SUBDLG_BTM                  358
#define IDB_TABCTRL_SELECT_BKGND_SPAN   359
#define IDB_TABCTRL_DESELECT_BKGND_LEFT 360
#define IDB_TABCTRL_DESELECT_BKGND_RIGHT 361
#define IDB_TABCTRL_DESELECT_BKGND_SPAN 362
#define IDB_TABCTRL_SELECT_BKGND_LEFT   363
#define IDB_TABCTRL_SELECT_BKGND_RIGHT  364
#define IDB_BTN_CANCEL2                 442
#define IDB_BTN_CANCEL                  443
#define IDB_BTN_CANCEL1                 443
#define IDB_BTN_OK                      444
#define IDB_REPOSITORY_PROPERTYDLG_SUBTITLE_L 445
#define IDB_REPOSITORY_PROPERTYDLG_SUBTITLE_M 446
#define IDB_REPOSITORY_PROPERTYDLG_SUBTITLE_R 447
#define IDB_REPOSITORY_PROPERTYDLG_SUBTITLE_C_ADD 448
#define IDB_REPOSITORY_PROPERTYDLG_SUBTITLE_G 449
#define IDB_REPOSITORY_PROPERTYDLG_SUBTITLE_G_ADD 449
#define IDB_REPOSITORY_PROPERTYDLG_SUBTITLE_SEARCH2 450
#define IDB_REPOSITORY_PROPERTYDLG_SUBTITLE_KEYWORD 450
#define IDB_REPOSITORY_PROPERTYDLG_SUBTITLE_SCRAP 451
#define IDB_REPOSITORY_PROPERTYDLG_SUBTITLE_SEARCH 452
#define IDB_REPOSITORY_PROPERTYDLG_TITLE1 453
#define IDB_REPOSITORY_PROPERTYDLG_TITLE 453
#define IDD_DLG_PROPERTIES              454
#define IDD_DLG_PROP_GENERAL            455
#define IDD_DLG_PROP_NETWORK            456
#define IDB_LOGINDLG_TITLE              457
#define IDB_LOGINDLG_AUTOLOGIN_T        458
#define IDB_LOGINDLG_BOX                459
#define IDB_LOGINDLG_HELP               460
#define IDB_LOGINDLG_ID_T               461
#define IDB_LOGINDLG_LOGINBTN_N         462
#define IDB_LOGINDLG_LOGINBTN_O         463
#define IDB_LOGINDLG_PASSWD_SAVE_T      464
#define IDB_LOGINDLG_PASSWD_T           465
#define IDD_DLG_LOGIN                   466
#define IDB_REPOSITORY_ANIMATE_NEW_ITEM 467
#define IDB_LISTCTRL_NEW_POST           468
#define IDB_BTN_PREV                    469
#define IDB_BTN_NEXT                    470
#define IDB_TABCTRL_PREV_N              471
#define IDB_TABCTRL_NEXT_N              472
#define IDB_LISTCTRL_COLUMNHEADER_START_O 473
#define IDB_LISTCTRL_COLUMNHEADER_END_O 474
#define IDB_LISTCTRL_COLUMNHEADER_SPAN_O 475
#define IDD_DRAG_DLG_TRANSPARENT        476
#define IDB_LOGINDLG_BTN_FIND_N         481
#define IDB_LOGINDLG_BTN_REG_D          482
#define IDB_LOGINDLG_BTN_REG_N          483
#define IDB_LOGINDLG_BTN_FIND_D         484
#define IDB_LOGINDLG_BG_CONTENTS        490
#define IDB_LOGINDLG_BG_TOP             491
#define IDB_LOGINDLG_BG_BOTTOM          492
#define IDB_LOGINDLG_BG_MID             493
#define IDB_BTN_CLOSE_N                 496
#define IDB_BTN_CLOSE_D                 497
#define IDB_BTN_PREV_N                  498
#define IDB_BTN_CANCEL_D                499
#define IDB_BTN_CANCEL_DISABLE          500
#define IDB_BTN_CANCEL_N                501
#define IDB_BTN_NEXT_D                  502
#define IDB_BTN_NEXT_DISABLE            503
#define IDB_BTN_NEXT_N                  504
#define IDB_BTN_OK_D                    505
#define IDB_BTN_OK_DISABLE              506
#define IDB_BTN_OK_N                    507
#define IDB_BTN_PREV_D                  508
#define IDB_BTN_PREV_DISABLE            509
#define IDB_SUBDLG_TITLE_RIGHT          510
#define IDB_SUBDLG_TITLE_LEFT           511
#define IDB_SUBDLG_TITLE_MID            512
#define IDB_REPOSITORY_PROPERTYDLG_SUBTITLE_SEARCH_MODIFY 513
#define IDB_REPOSITORY_PROPERTYDLG_SUBTITLE_C_MODIFY 514
#define IDB_REPOSITORY_PROPERTYDLG_SUBTITLE_G_MODIFY 515
#define IDB_REPOSITORY_PROPERTYDLG_SUBTITLE_KEYWORD_MODIFY 516
#define IDB_REPOSITORY_PROPERTYDLG_SUBTITLE_SCRAP_MODIFY 517
#define IDB_REPOSITORY_PROPERTYDLG_BOX  518
#define IDB_MAINFRAME_TOP_SPAN          519
#define IDB_REPOSITORY_GRP_EXPANDED_N   520
#define IDB_REPOSITORY_GRP_EXPANDED_O   521
#define IDB_REPOSITORY_GRP_EXPANDED_P   522
#define IDB_REPOSITORY_DLG_BKGND_TOP    523
#define IDB_REPOSITORY_DLG_BKGND_BOTTOM 524
#define IDB_REPOSITORY_DLG_BKGND_LEFT   525
#define IDB_REPOSITORY_DLG_BKGND_RIGHT  526
#define IDB_REPOSITORY_GROUP_BG_S       527
#define IDD_DLG_MESSAGE_BOX             528
#define IDD_DLG_STYLE                   530
#define IDB_MB_QUESTION                 531
#define IDB_MB_ASTERISK                 532
#define IDB_MB_EXCLAMATION              533
#define IDB_MB_HAND                     534
#define IDB_BTN_YES_N                   535
#define IDB_BTN_NOALL_D                 536
#define IDB_BTN_NOALL_DISABLE           537
#define IDB_BTN_NOALL_N                 538
#define IDB_BTN_NO_D                    539
#define IDB_BTN_NO_DISABLE              540
#define IDB_BTN_NO_N                    541
#define IDB_BTN_YESALL_N                542
#define IDB_BTN_YESALL_D                543
#define IDB_BTN_YESALL_DISABLE          544
#define IDB_BTN_YES_D                   545
#define IDB_BTN_YES_DISABLE             546
#define IDD_DLG_SCRAP_MANAGER           547
#define IDR_SCRAP_MGR                   548
#define IDR_POSTSAVE_XSLT               549
#define IDB_BTN_DOT_D                   553
#define IDB_BTN_DOT_N                   554
#define IDB_BTN_APPLY_D                 555
#define IDB_BTN_APPLY_DISABLE           556
#define IDB_BTN_APPLY_N                 557
#define IDB_BTN_YES_O                   558
#define IDB_BTN_APPLY_O                 559
#define IDB_BTN_CANCEL_O                560
#define IDB_BTN_NEXT_O                  561
#define IDB_BTN_NOALL_O                 562
#define IDB_BTN_NO_O                    563
#define IDB_BTN_OK_O                    564
#define IDB_BTN_PREV_O                  565
#define IDB_BTN_YESALL_O                566
#define IDB_REPOSITORY_PROPERTYDLG_ICON_CHANNEL 567
#define IDB_REPOSITORY_PROPERTYDLG_ICON_GROUP 568
#define IDB_REPOSITORY_PROPERTYDLG_ICON_KEYWORD 569
#define IDB_REPOSITORY_PROPERTYDLG_ICON_SCRAP 570
#define IDD_DIALOG1                     571
#define IDD_DLG_OPMLIMPORT              572
#define IDD_DLG_PROP_STYLE              573
#define IDB_REPOSITORY_GRP_EXPANDED2_N  575
#define IDB_REPOSITORY_GRP_EXPANDED2_O  576
#define IDB_REPOSITORY_GRP_EXPANDED2_P  577
#define IDC_TREE_REPOSITORY             1001
#define IDC_LIST1                       1002
#define IDC_LIST_RSS                    1002
#define IDC_LIST_PROPERTIES             1002
#define IDC_LIST_RSSURL                 1002
#define IDC_LIST_STYLE                  1002
#define IDC_LIST_MENU                   1002
#define IDC_COMBO_GO                    1005
#define IDC_BUTTON1                     1006
#define IDC_BTN_ADDGROUP                1006
#define IDC_INFORMATION_GOTO_MAINLIST_BTN 1006
#define IDC_BUTTON2                     1007
#define IDC_BTN_ADDCHANNEL              1007
#define IDC_BUTTON3                     1008
#define IDC_BTN_DELITEM                 1008
#define IDC_BUTTON4                     1009
#define IDC_BTN_MODIFYITEM              1009
#define IDC_EDIT1                       1010
#define IDC_EDIT_TITLE                  1010
#define IDC_EDIT_PORT                   1010
#define IDC_EDIT_USERPATH               1010
#define IDC_EDIT_ID                     1010
#define IDC_EDIT_OPMLLOCATION           1010
#define IDC_EDIT_PAPERSTYLE             1010
#define IDC_EDIT2                       1011
#define IDC_EDIT_COMMENT                1011
#define IDC_EDIT_MAXUPLOAD              1011
#define IDC_EDIT_PASSWD                 1011
#define IDC_EDIT3                       1012
#define IDC_EDIT_INTERVAL               1012
#define IDC_EDIT_MAXDOWNLOAD            1012
#define IDC_EDIT4                       1013
#define IDC_EDIT_XML                    1013
#define IDC_EDIT5                       1014
#define IDC_EDIT_HTML                   1014
#define IDC_SPLITTER_VERT_1             1015
#define IDC_EDIT_KEYWORD                1015
#define IDC_SPLITTER_HORIZ_1            1016
#define IDC_BTN_ADDSCRAP                1018
#define IDC_BTN_ADDKEYWORD              1019
#define IDC_BTN_REFRESH                 1020
#define IDC_EDIT_SEARCH                 1021
#define IDC_BUTTON_SEARCH               1022
#define IDC_BUTTON_SRCH                 1022
#define IDC_CPD_PORT                    1023
#define IDC_STATIC_HTML                 1023
#define IDC_BUTTON_TAG                  1023
#define IDC_STATIC_XML                  1024
#define IDC_STATIC_INTERVAL             1025
#define IDC_STATIC_COMMENT              1026
#define IDC_STATIC_TITLE                1027
#define IDC_STATIC_MIN                  1028
#define IDC_BTN_SRCH_R_N                1028
#define IDC_VIEWLIST_FUNCTION_SAVE      1028
#define IDC_STATIC_TARGET_GROUP         1028
#define IDC_STATIC_KEYWORD              1029
#define IDC_BTN_NETWORK                 1029
#define IDC_VIEWLIST_FUNCTION_STYLE     1029
#define IDC_BTN_SRCH_R                  1030
#define IDC_VIEWLIST_FUNCTION_NEWTAB    1030
#define IDC_BTN_SRCH_ALL                1031
#define IDC_VIEWLIST_FUNCTION_SUBSCRIBE 1031
#define IDC_BTN_SRCH_LOCAL              1032
#define IDC_BTN_NETWORK_LOAD            1033
#define IDC_BUTTON5                     1033
#define IDC_BTN_DBLNEXT                 1033
#define IDC_BUTTON6                     1034
#define IDC_BTN_LAST                    1034
#define IDC_POST_BTN                    1035
#define IDC_BTN_FIRST                   1036
#define IDC_BTN_DBLBACK                 1037
#define IDC_BTN_BACK                    1038
#define IDC_BTN_NEXT                    1039
#define IDC_CHK_AUTOSTART               1040
#define IDC_CHK_SAVEPASS                1041
#define IDC_CHK_AUTOLOGIN               1042
#define IDC_CHK_USEINFORMWND            1043
#define IDC_BTN_APPLY                   1044
#define IDC_CHK_CLOSEEXIT               1044
#define IDC_BUTTON_USERPATH             1045
#define IDC_STATIC_FIND                 1046
#define IDC_CHK_SEARCHALWAYSSAVE        1046
#define IDC_CHECK_AUTO_LOGIN            1047
#define IDC_CHECK_PASSWD_SAVE           1048
#define IDC_STATIC_REG                  1049
#define IDC_STATIC_WIZARD_COMMENT       1050
#define IDC_COMBO_INTERVAL              1051
#define IDC_COMBO_TARGET_GROUP          1052
#define IDC_CHECK_AUTO_SEARCH           1053
#define IDC_EXPLORER                    1054
#define IDC_SCRAPLIST                   1055
#define IDC_MSG                         1056
#define IDC_STATIC_MSG                  1056
#define ID_SUMMIT                       1057
#define ID_CANCEL                       1058
#define IDC_STATIC_LINKMSG              1059
#define IDC_ADDRESS_MSG                 1060
#define IDC_CHECK_ISSEARCH              1061
#define IDC_STATIC_SEARCHALWAYSSAVE     1062
#define IDC_STATIC_SEARCH               1062
#define IDC_STATIC_NORMAL               1063
#define IDC_STATIC_RUN                  1064
#define IDC_STATIC_INFOWND              1065
#define IDC_STATIC_USERPATH             1066
#define IDC_STATIC_NETWORK              1067
#define IDC_STATIC_PORT                 1068
#define IDC_STATIC_CONN_PORT            1069
#define IDC_STATIC_TRANSLIMIT           1070
#define IDC_STATIC_UPLOAD               1071
#define IDC_STATIC_DOWNLOAD             1072
#define IDC_STATIC_MAX                  1073
#define IDC_STATIC_MAX2                 1074
#define IDC_BTN_FILEDLG                 1076
#define IDC_BTN_OK                      1077
#define IDC_BTN_CANCEL                  1078
#define IDC_STATIC_STYLE                1079
#define IDC_STATIC_SUMMARY              1080
#define IDC_CHECK_SUMMARY               1081
#define IDC_STATIC_PAPERSTYLE           1082
#define ID_ALT_D_FOCUS_ON_ADDRBAR       32771
#define ID_FEED_CHANNEL                 32772
#define ID_REPOS_CM_REFRESH             32772
#define ID_VIEW_CHANNELPOST             32773
#define ID_VIEW_CHANNELPOST_ALL         32773
#define ID_TRAY_OPEN                    32774
#define ID_TRAY_EXIT                    32775
#define ID_REPOS_CM_ADD_GROUP           32776
#define ID_REPOS_CM_ADD_CHANNEL         32777
#define ID_REPOS_CM_ADD_SCRAP           32778
#define ID_REPOS_CM_ADD_KEYWORD         32779
#define ID_REPOS_CM_OPML_READ           32780
#define ID_REPOS_CM_OPML_IMPORT         32780
#define ID_REPOS_CM_DELETE              32781
#define ID_REPOS_CM_RENAME              32782
#define ID_REPOS_CM_PROPERTY            32783
#define ID_LIST_HD_PUBLISHER            32784
#define ID_LIST_HD_SUBJECT              32785
#define ID_LIST_HD_DATE                 32786
#define ID_LIST_HD_RANK                 32787
#define ID_LIST_HD_AUTHOR               32788
#define ID_LIST_ITEM_DELETE             32791
#define ID_LIST_ITEM_GENERATE_HTML      32792
#define ID_VIEW_CHANNELPOST_UNREAD      32793
#define ID_PROPERTIES                   32794
#define ID_VIEW_CHANNEL_MARK_AS_READ    32795
#define ID_VIEW_CHANNEL_MARK_AS_UNREAD  32796
#define ID_REPOS_CM_OPML_EXPORT         32797
#define ID_FOCUSON_ADDR_COMBO           32798
#define ID_CREATE_NEW_SCRAP_MGR         32799
#define ID_SCRAP_BASE_UID               32800
#define ID_LIST_ITEM_GOLINK             33100
#define IDS_ASSIGNEDFISH                61446

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        578
#define _APS_NEXT_COMMAND_VALUE         33101
#define _APS_NEXT_CONTROL_VALUE         1083
#define _APS_NEXT_SYMED_VALUE           125
#endif
#endif
